github.com:
    users:
        faraaz-bot:
            oauth_token: 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
    git_protocol: ssh
    oauth_token: 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
    user: faraaz-bot
